version = 0.1

[default.deploy.parameters]
stack_name = "sprintwise-api"
resolve_s3 = true
s3_prefix = "sprintwise-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-2"
